name: moose-assist
envs:
  - key: APIKEY
    scope: RUN_AND_BUILD_TIME
    value: "SEBIEJTAEFRNWFSJBLJVTREQICBZVLORWZVLJHKSYTCJZZPATQSSHABBKEAGULFRLTVJQTRZRIRLHAMEUOWKROQZIINR"
services:
  - name: web
    github:
      repo: szegedim/moose-assist
      branch: main